// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDefaultInstallParams():Promise<main.InstallParams>;

export function Greet(arg1:string):Promise<string>;

export function InstallExecute(arg1:main.InstallParams):Promise<void>;

export function Quit():Promise<void>;

export function SelectDirectoryDialog(arg1:string):Promise<string>;
