// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultInstallParams() {
  return window['go']['main']['App']['GetDefaultInstallParams']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallExecute(arg1) {
  return window['go']['main']['App']['InstallExecute'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SelectDirectoryDialog(arg1) {
  return window['go']['main']['App']['SelectDirectoryDialog'](arg1);
}
